Areas/Blog/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using aspnetcoremvc.Models;
using aspnetcoremvc.Models.Blog;

namespace aspnetcoremvc.Areas.Blog.Controllers
{
    [Area("Blog")]
    [Route("admin/blog/[action]")]
    public class CategoryController : Controller
    {
        private readonly AppMvcContext _context;

        public CategoryController(AppMvcContext context)
        {
            _context = context;
        }

        public void CreateSelectItem(List<Category> categories, List<Category> data, int level = 0){
            string prefix = String.Concat(Enumerable.Repeat("----", level));
            foreach(Category item in categories){
                item.Title = prefix + item.Title;
                data.Add(item);
                if(item.CategoryChildren.Count > 0){
                    CreateSelectItem(item.CategoryChildren.ToList(), data, level + 1);
                }
            }
        }
        // GET: Category
        public async Task<IActionResult> Index()
        {
            var appMvcContext = await _context.Categories
            .Include(c => c.ParentCategory)
            .Include(c => c.CategoryChildren)
            .ToListAsync();

            var result = (from c in appMvcContext where c.ParentCategoryId == null select c).ToList();
            return View(result);
        }

        // GET: Category/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .Include(c => c.ParentCategory)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Category/Create
        public async Task<IActionResult> Create()
        {
            var appMvcContext = _context.Categories
            .Include(c => c.ParentCategory)
            .Include(c => c.CategoryChildren);

            var result = await (from c in appMvcContext where c.ParentCategoryId == null select c).ToListAsync();
            List<Category> data = new List<Category>();
            data.Insert(0, new Category()
            {
                Id = -1,
                Title = "Khong co danh muc cha"
            });
            CreateSelectItem(result,data,0);
            var selectList = new SelectList(data, "Id", "Title");
            ViewData["ParentCategoryId"] = selectList;
            return View();
        }

        // POST: Category/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([FromForm] Category category)
        {
            if(category.ParentCategoryId == -1) category.ParentCategoryId = null;
            if (ModelState.IsValid)
            {
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

             ViewData["ParentCategoryId"] = new SelectList(_context.Categories, "Id", "Slug", category.ParentCategoryId);
            return View(category);
        }

        // GET: Category/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            var appMvcContext = _context.Categories
            .Include(c => c.ParentCategory)
            .Include(c => c.CategoryChildren);

            var result = await (from c in appMvcContext where c.ParentCategoryId == null select c).ToListAsync();
            List<Category> data = new List<Category>();
            data.Insert(0, new Category()
            {
                Id = -1,
                Title = "Khong co danh muc cha"
            });
            CreateSelectItem(result,data,0);
            var selectList = new SelectList(data, "Id", "Title");
            ViewData["ParentCategoryId"] = selectList;
            //ViewData["ParentCategoryId"] = new SelectList(_context.Categories, "Id", "Slug", category.ParentCategoryId);
            return View(category);
        }

        // POST: Category/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Content,Slug,ParentCategoryId")] Category category)
        {
            if (id != category.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                if(category.ParentCategoryId == -1) category.ParentCategoryId = null;
                try
                {
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ParentCategoryId"] = new SelectList(_context.Categories, "Id", "Slug", category.ParentCategoryId);
            return View(category);
        }

        // GET: Category/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .Include(c => c.ParentCategory)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Category/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var category = await _context.Categories.FindAsync(id);
            if(category == null){
                return NotFound();
            }

            var categories = _context.Categories.Include(c => c.CategoryChildren);

            var result = (from c in categories where c.Id == id select c).FirstOrDefault();


            foreach(var c in result.CategoryChildren){
                c.ParentCategoryId = category.ParentCategoryId;
            }
            if (category != null)
            {
                _context.Categories.Remove(category);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
            return _context.Categories.Any(e => e.Id == id);
        }
    }
}

Areas/Blog/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using aspnetcoremvc.Models;
using aspnetcoremvc.Models.Blog;
using aspnetcoremvc.Areas.Blog.Model;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace aspnetcoremvc.Areas.Blog.Controllers
{
    [Area("Blog")]
    [Route("admin/post/[action]/{id?}")]
    [Authorize]
    public class PostController : Controller
    {
        private readonly AppMvcContext _context;
        private readonly UserManager<AppUser> _userManager;


        public PostController(AppMvcContext context, UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Post
        public async Task<IActionResult> Index(int? pageNumber)
        {
            var posts = _context.Posts.Include(p => p.Author).OrderByDescending(p => p.DateUpdated);
            return View(await PaginatedList<Post>.CreateAsync(posts, pageNumber ?? 1, 10));
        }

        // GET: Post/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts
                .Include(p => p.Author)
                .FirstOrDefaultAsync(m => m.PostId == id);
            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        // GET: Post/Create
        public IActionResult Create()
        {
            ViewData["CategoriesId"] = new SelectList(_context.Categories, "Id", "Title");
            return View();
        }

        // POST: Post/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Title,Description,Slug,Content,Published, CategoriesId")] CreatePostModel post)
        {
            var user = await _userManager.GetUserAsync(this.User);
            if (user == null)
            {
                ModelState.AddModelError("AuthorId", "Invalid author.");
                ViewData["AuthorId"] = new SelectList(_context.Users, "Id", "Id", post.AuthorId);
                return View(post);
            }
            post.AuthorId = user.Id;
            post.DateCreated = post.DateUpdated = DateTime.Now;
            if (ModelState.IsValid)
            {

                _context.Add(post);
                foreach (var CateId in post.CategoriesId)
                {
                    _context.Add(new PostCategory()
                    {
                        CategoryID = CateId,
                        Post = post
                    });
                }
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoriesId"] = new SelectList(_context.Categories, "Id", "Title");
            return View(post);
        }

        // GET: Post/Edit/5
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts
                                .Include(p => p.PostCategories)
                                .Where(p => p.PostId == id)
                                .FirstOrDefaultAsync();
            if (post == null)
            {
                return NotFound();
            }
            var postEdit = new CreatePostModel()
            {
                PostId = post.PostId,
                Title = post.Title,
                Content = post.Content,
                Description = post.Description,
                Slug = post.Slug,
                Published = post.Published,
                CategoriesId = post.PostCategories.Select(pc => pc.CategoryID).ToArray()
            };

            if (post == null)
            {
                return NotFound();
            }
            ViewData["CategoriesId"] = new SelectList(_context.Categories, "Id", "Title");
            return View(postEdit);
        }

        // POST: Post/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PostId,Title,Description,Slug,Content,Published, CategoriesId")] CreatePostModel post)
        {
            if (id != post.PostId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {

                    var postUpdate = await _context.Posts.Include(p => p.PostCategories).FirstOrDefaultAsync(p => p.PostId == id);
                    if (postUpdate == null)
                    {
                        return NotFound();
                    }

                    postUpdate.Title = post.Title;
                    postUpdate.Description = post.Description;
                    postUpdate.Content = post.Content;
                    postUpdate.Published = post.Published;
                    postUpdate.Slug = post.Slug;
                    postUpdate.DateUpdated = DateTime.Now;

                    // Update PostCategory
                    if (post.CategoriesId == null) post.CategoriesId = new int[] { };

                    var oldCateIds = postUpdate.PostCategories.Select(c => c.CategoryID).ToArray();
                    var newCateIds = post.CategoriesId;

                    var removeCatePosts = from postCate in postUpdate.PostCategories
                                          where (!newCateIds.Contains(postCate.CategoryID))
                                          select postCate;
                    _context.PostCategories.RemoveRange(removeCatePosts);

                    var addCateIds = from CateId in newCateIds
                                     where !oldCateIds.Contains(CateId)
                                     select CateId;

                    foreach (var CateId in addCateIds)
                    {
                        _context.PostCategories.Add(new PostCategory()
                        {
                            PostID = id,
                            CategoryID = CateId
                        });
                    }

                    Console.WriteLine("cccccccccccccccccccccccccccccccccc");
                    _context.Update(postUpdate);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PostExists(post.PostId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoriesId"] = new SelectList(_context.Categories, "Id", "Title");
            return View(post);
        }

        // GET: Post/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts
                .Include(p => p.Author)
                .FirstOrDefaultAsync(m => m.PostId == id);
            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        // POST: Post/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var post = await _context.Posts.FindAsync(id);
            if (post != null)
            {
                _context.Posts.Remove(post);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PostExists(int id)
        {
            return _context.Posts.Any(e => e.PostId == id);
        }
    }
}

Areas/ProductManage/Controllers/StarController.cs
using aspnetcoremvc.Services;
using Microsoft.AspNetCore.Mvc;

namespace aspnetcoremvc.Controllers;
[Area("ProductManage")]
public class StarController : Controller
{

    private readonly StarService _starService;
    private readonly ILogger<HomeController> _logger;

    public StarController(StarService starService, ILogger<HomeController> logger)
    {
        _starService = starService;
        _logger = logger;
    }
    public IActionResult Index()
    {
        return View();
    }
    // 
    // GET: /HelloWorld/Welcome/ 
    public IActionResult Detail(int id)
    {
        var result = _starService.stars.Where(star => star.Id == id).FirstOrDefault();
        return View("Detail", result);
    }
}

Views/Shared/_AlertMessage.cshtml
@{
    var status = TempData["StatusMessage"] as string;
    bool boolean = string.IsNullOrEmpty(status);
}
@if(!boolean){
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        @status
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - aspnetcoremvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <link rel="stylesheet" href="~/lib/summernote-bs4.min.css" />
    <script src="~/lib/summernote-bs4.min.js"></script>


    <link rel="stylesheet" href="~/aspnetcoremvc.styles.css" asp-append-version="true" />



</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid mx-5">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">aspnetcoremvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Star" asp-action="Index">Star</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                    <partial name="_MenuPartial" />

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - aspnetcoremvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_MenuPartial.cshtml
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService authorizationService

@{
    var result = await authorizationService.AuthorizeAsync(this.User, "ViewManageMenu");
}

@if(result.Succeeded){
    <div class="dropdown">
    <a class="btn btn-secondary dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        Manage
    </a>

    <ul class="dropdown-menu">
        <li><a class="dropdown-item" asp-action="Index" asp-controller="Category" asp-area="Blog">Quản lí danh mục</a></li>
        <li><a class="dropdown-item" asp-action="Index" asp-controller="User" asp-area="Identity">Quản lí người dùng</a></li>
        <li><a class="dropdown-item" asp-action="Index" asp-controller="Post" asp-area="Blog">Quản lí bài viết</a></li>
        <li><a class="dropdown-item" asp-action="Index" asp-controller="DbManage" asp-area="Database">Quản lí bài viết</a></li>
    </ul>
    </div>
}

Views/Shared/_SummerNotePartial.cshtml
@model aspnetcoremvc.Models.SummerNote

<script>
    $(document).ready(function () {
        $('@Model.ID').summernote({
            tabsize: 2,
            height: @Model.Height,
            toolbar: @Html.Raw(@Model.ToolBar)
        });
    });
</script>